/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFRAM;

import CATEGORIAS_FRAME.*;

/**
 *
 * @author cesar
 */
public class CategoriasFrame extends javax.swing.JFrame {
    
    int xMouse, yMouse;

    /**
     * Creates new form CategoriasFrame
     */
    imagen_posicion image_escalar =new imagen_posicion();
    
    public CategoriasFrame() {
        initComponents();
        image_escalar.escaralarLabel(label_fondo_spider, "/imagenes/fondo_categoria.jpg");
        image_escalar.escaralarLabel(label_cine, "/imagenes/logo_cine.jpg");
        image_escalar.escaralarLabel(label_deporte, "/imagenes/logo_deporte.jpg");
        image_escalar.escaralarLabel(label_eventos, "/imagenes/logo_eventos_historicos.jpg");
        image_escalar.escaralarLabel(label_ciencia, "/imagenes/logo_ciencia.png");
        image_escalar.escaralarLabel(label_geografia, "/imagenes/logo_geografia.jpg");
        image_escalar.escaralarLabel(label_culturaGeneral, "/imagenes/logo_cultura_general.jpg");
        image_escalar.escaralarLabel(label_entretenimiento, "/imagenes/logo_entretenimiento.jpg");
        image_escalar.escaralarLabel(label_arte, "/imagenes/logo_arte.png");
        image_escalar.escaralarLabel(label_tecnologia, "/imagenes/logo_tecnologia.jpg");
        image_escalar.escaralarLabel(label_astronomia, "/imagenes/logo_astronomia.jpg");        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        label_fondo_spider = new javax.swing.JLabel();
        label_categorias = new javax.swing.JLabel();
        jSeparator1_categoria = new javax.swing.JSeparator();
        panel_cine = new javax.swing.JPanel();
        label_cine = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        panel_deporte = new javax.swing.JPanel();
        label_deporte = new javax.swing.JLabel();
        panel_eventos = new javax.swing.JPanel();
        label_eventos = new javax.swing.JLabel();
        panel_ciencia = new javax.swing.JPanel();
        label_ciencia = new javax.swing.JLabel();
        panel_geografia = new javax.swing.JPanel();
        label_geografia = new javax.swing.JLabel();
        panel_cultura = new javax.swing.JPanel();
        label_culturaGeneral = new javax.swing.JLabel();
        panel_entretenimiento = new javax.swing.JPanel();
        label_entretenimiento = new javax.swing.JLabel();
        panel_arte = new javax.swing.JPanel();
        label_arte = new javax.swing.JLabel();
        panel_tecnologia = new javax.swing.JPanel();
        label_tecnologia = new javax.swing.JLabel();
        panel_astronomia = new javax.swing.JPanel();
        label_astronomia = new javax.swing.JLabel();
        labelCine = new javax.swing.JLabel();
        labelDeporte = new javax.swing.JLabel();
        labelEventos = new javax.swing.JLabel();
        labelCiencia = new javax.swing.JLabel();
        labelGeografia = new javax.swing.JLabel();
        labelCulturaGeneral = new javax.swing.JLabel();
        labelEntretenimiento = new javax.swing.JLabel();
        labelarte = new javax.swing.JLabel();
        labelTecnologia = new javax.swing.JLabel();
        labelAstronomia = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_fondo_spider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_fondo_spider, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 540, 790));

        label_categorias.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        label_categorias.setForeground(new java.awt.Color(0, 0, 0));
        label_categorias.setText("CATEGORIA DE TEMAS");
        label_categorias.setToolTipText("");
        jPanel1.add(label_categorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 470, 60));

        jSeparator1_categoria.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1_categoria.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 470, 10));

        label_cine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_cine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_cine.setFocusCycleRoot(true);
        label_cine.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_cine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_cineMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_cineLayout = new javax.swing.GroupLayout(panel_cine);
        panel_cine.setLayout(panel_cineLayout);
        panel_cineLayout.setHorizontalGroup(
            panel_cineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cineLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_cine, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_cineLayout.setVerticalGroup(
            panel_cineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_cine, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        jPanel1.add(panel_cine, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 120, 90));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 120, 80));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 120, 80));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 120, 80));

        label_deporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_deporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_deporteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_deporteLayout = new javax.swing.GroupLayout(panel_deporte);
        panel_deporte.setLayout(panel_deporteLayout);
        panel_deporteLayout.setHorizontalGroup(
            panel_deporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_deporteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_deporte, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_deporteLayout.setVerticalGroup(
            panel_deporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_deporte, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel1.add(panel_deporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 120, 100));

        label_eventos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_eventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_eventosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_eventosLayout = new javax.swing.GroupLayout(panel_eventos);
        panel_eventos.setLayout(panel_eventosLayout);
        panel_eventosLayout.setHorizontalGroup(
            panel_eventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_eventos, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        panel_eventosLayout.setVerticalGroup(
            panel_eventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_eventos, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel1.add(panel_eventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 120, 80));

        label_ciencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_ciencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_cienciaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_cienciaLayout = new javax.swing.GroupLayout(panel_ciencia);
        panel_ciencia.setLayout(panel_cienciaLayout);
        panel_cienciaLayout.setHorizontalGroup(
            panel_cienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_ciencia, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        panel_cienciaLayout.setVerticalGroup(
            panel_cienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_ciencia, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel1.add(panel_ciencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        label_geografia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_geografia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_geografiaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_geografiaLayout = new javax.swing.GroupLayout(panel_geografia);
        panel_geografia.setLayout(panel_geografiaLayout);
        panel_geografiaLayout.setHorizontalGroup(
            panel_geografiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_geografia, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        panel_geografiaLayout.setVerticalGroup(
            panel_geografiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_geografia, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel1.add(panel_geografia, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 120, 80));

        label_culturaGeneral.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_culturaGeneral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_culturaGeneralMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_culturaLayout = new javax.swing.GroupLayout(panel_cultura);
        panel_cultura.setLayout(panel_culturaLayout);
        panel_culturaLayout.setHorizontalGroup(
            panel_culturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_culturaGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        panel_culturaLayout.setVerticalGroup(
            panel_culturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_culturaGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel1.add(panel_cultura, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 120, 80));

        label_entretenimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_entretenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_entretenimientoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_entretenimientoLayout = new javax.swing.GroupLayout(panel_entretenimiento);
        panel_entretenimiento.setLayout(panel_entretenimientoLayout);
        panel_entretenimientoLayout.setHorizontalGroup(
            panel_entretenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_entretenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        panel_entretenimientoLayout.setVerticalGroup(
            panel_entretenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_entretenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        );

        jPanel1.add(panel_entretenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        label_arte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_arte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_arteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_arteLayout = new javax.swing.GroupLayout(panel_arte);
        panel_arte.setLayout(panel_arteLayout);
        panel_arteLayout.setHorizontalGroup(
            panel_arteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_arte, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        panel_arteLayout.setVerticalGroup(
            panel_arteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_arte, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel1.add(panel_arte, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 120, 80));

        label_tecnologia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_tecnologia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_tecnologiaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_tecnologiaLayout = new javax.swing.GroupLayout(panel_tecnologia);
        panel_tecnologia.setLayout(panel_tecnologiaLayout);
        panel_tecnologiaLayout.setHorizontalGroup(
            panel_tecnologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_tecnologia, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        panel_tecnologiaLayout.setVerticalGroup(
            panel_tecnologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_tecnologia, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel1.add(panel_tecnologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 120, 80));

        label_astronomia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_astronomia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_astronomiaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_astronomiaLayout = new javax.swing.GroupLayout(panel_astronomia);
        panel_astronomia.setLayout(panel_astronomiaLayout);
        panel_astronomiaLayout.setHorizontalGroup(
            panel_astronomiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_astronomia, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        panel_astronomiaLayout.setVerticalGroup(
            panel_astronomiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_astronomia, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        jPanel1.add(panel_astronomia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 610, 140, 90));

        labelCine.setBackground(new java.awt.Color(0, 0, 0));
        labelCine.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelCine.setForeground(new java.awt.Color(0, 0, 0));
        labelCine.setText("CINE");
        jPanel1.add(labelCine, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 80, -1));

        labelDeporte.setBackground(new java.awt.Color(0, 0, 0));
        labelDeporte.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelDeporte.setForeground(new java.awt.Color(0, 0, 0));
        labelDeporte.setText("DEPORTE");
        jPanel1.add(labelDeporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        labelEventos.setBackground(new java.awt.Color(0, 0, 0));
        labelEventos.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelEventos.setForeground(new java.awt.Color(0, 0, 0));
        labelEventos.setText("EVENTOS HISTORICOS");
        jPanel1.add(labelEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        labelCiencia.setBackground(new java.awt.Color(0, 0, 0));
        labelCiencia.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelCiencia.setForeground(new java.awt.Color(0, 0, 0));
        labelCiencia.setText("CIENCIA");
        jPanel1.add(labelCiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        labelGeografia.setBackground(new java.awt.Color(0, 0, 0));
        labelGeografia.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelGeografia.setForeground(new java.awt.Color(0, 0, 0));
        labelGeografia.setText("GEOGRAFIA");
        jPanel1.add(labelGeografia, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, -1, -1));

        labelCulturaGeneral.setBackground(new java.awt.Color(0, 0, 0));
        labelCulturaGeneral.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelCulturaGeneral.setForeground(new java.awt.Color(0, 0, 0));
        labelCulturaGeneral.setText("CULTURA GENERAL");
        jPanel1.add(labelCulturaGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, -1, -1));

        labelEntretenimiento.setBackground(new java.awt.Color(0, 0, 0));
        labelEntretenimiento.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelEntretenimiento.setForeground(new java.awt.Color(0, 0, 0));
        labelEntretenimiento.setText("ENTRETENIMIENTO");
        jPanel1.add(labelEntretenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, -1, -1));

        labelarte.setBackground(new java.awt.Color(0, 0, 0));
        labelarte.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelarte.setForeground(new java.awt.Color(0, 0, 0));
        labelarte.setText("ARTE");
        jPanel1.add(labelarte, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, -1, -1));

        labelTecnologia.setBackground(new java.awt.Color(0, 0, 0));
        labelTecnologia.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelTecnologia.setForeground(new java.awt.Color(0, 0, 0));
        labelTecnologia.setText("TECNOLOGIA");
        jPanel1.add(labelTecnologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 570, -1, -1));

        labelAstronomia.setBackground(new java.awt.Color(0, 0, 0));
        labelAstronomia.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelAstronomia.setForeground(new java.awt.Color(0, 0, 0));
        labelAstronomia.setText("ASTRONOMIA");
        jPanel1.add(labelAstronomia, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 710, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("  X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jLabel1.getAccessibleContext().setAccessibleDescription("");

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x- xMouse, y-yMouse);
        
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        
        xMouse= evt.getX();
        
        yMouse= evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void label_cineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_cineMouseClicked
        // TODO add your handling code here:
        CINE llamadaCine = new CINE();
        llamadaCine.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_label_cineMouseClicked

    private void label_deporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_deporteMouseClicked
        // TODO add your handling code here:
        DEPORTE llamadaDeporte= new DEPORTE();
        llamadaDeporte.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_label_deporteMouseClicked

    private void label_eventosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_eventosMouseClicked
        // TODO add your handling code here:
        EVENTOS_HISTORICOS llamadaEventos =new EVENTOS_HISTORICOS();
        llamadaEventos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_label_eventosMouseClicked

    private void label_cienciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_cienciaMouseClicked
        // TODO add your handling code here:
        CIENCIA llamadaCiencia = new CIENCIA();
        llamadaCiencia.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_label_cienciaMouseClicked

    private void label_geografiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_geografiaMouseClicked
        // TODO add your handling code here:
        GEOGRAFIA llamadaGeografia = new GEOGRAFIA();
        llamadaGeografia.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_label_geografiaMouseClicked

    private void label_culturaGeneralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_culturaGeneralMouseClicked
        // TODO add your handling code here:
        CULTURA_GENERAL llamadaCultura= new CULTURA_GENERAL();
        llamadaCultura.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_label_culturaGeneralMouseClicked

    private void label_entretenimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_entretenimientoMouseClicked
        // TODO add your handling code here:
        ENTRETENIMIENTO llamadaEntretenimiento=new ENTRETENIMIENTO();
        llamadaEntretenimiento.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_label_entretenimientoMouseClicked

    private void label_arteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_arteMouseClicked
        // TODO add your handling code here:
        ARTE llamadaArte = new ARTE();
        llamadaArte.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_label_arteMouseClicked

    private void label_tecnologiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_tecnologiaMouseClicked
        // TODO add your handling code here:
        TECNOLOGIA llamadaTecnologia = new TECNOLOGIA();
        llamadaTecnologia.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_label_tecnologiaMouseClicked

    private void label_astronomiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_astronomiaMouseClicked
        // TODO add your handling code here:
        ASTRONOMIA llamadaAstronomia = new ASTRONOMIA();
        llamadaAstronomia.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_label_astronomiaMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CategoriasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CategoriasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CategoriasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategoriasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CategoriasFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1_categoria;
    private javax.swing.JLabel labelAstronomia;
    private javax.swing.JLabel labelCiencia;
    private javax.swing.JLabel labelCine;
    private javax.swing.JLabel labelCulturaGeneral;
    private javax.swing.JLabel labelDeporte;
    private javax.swing.JLabel labelEntretenimiento;
    private javax.swing.JLabel labelEventos;
    private javax.swing.JLabel labelGeografia;
    private javax.swing.JLabel labelTecnologia;
    private javax.swing.JLabel label_arte;
    private javax.swing.JLabel label_astronomia;
    private javax.swing.JLabel label_categorias;
    private javax.swing.JLabel label_ciencia;
    private javax.swing.JLabel label_cine;
    private javax.swing.JLabel label_culturaGeneral;
    private javax.swing.JLabel label_deporte;
    private javax.swing.JLabel label_entretenimiento;
    private javax.swing.JLabel label_eventos;
    private javax.swing.JLabel label_fondo_spider;
    private javax.swing.JLabel label_geografia;
    private javax.swing.JLabel label_tecnologia;
    private javax.swing.JLabel labelarte;
    private javax.swing.JPanel panel_arte;
    private javax.swing.JPanel panel_astronomia;
    private javax.swing.JPanel panel_ciencia;
    private javax.swing.JPanel panel_cine;
    private javax.swing.JPanel panel_cultura;
    private javax.swing.JPanel panel_deporte;
    private javax.swing.JPanel panel_entretenimiento;
    private javax.swing.JPanel panel_eventos;
    private javax.swing.JPanel panel_geografia;
    private javax.swing.JPanel panel_tecnologia;
    // End of variables declaration//GEN-END:variables
}
